name: auth_app_using_google_and_facebook_sign_in
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  modal_progress_hud_nsn: ^0.5.1
  awesome_dialog: ^3.2.1
  cupertino_icons: ^1.0.8

  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6

  google_sign_in: ^6.3.0

  validators: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf